# Generated by Django 5.1.3 on 2024-11-23 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('description', models.TextField()),
                ('condition', models.CharField(max_length=50)),
                ('vin', models.CharField(max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('seller_notes', models.TextField(blank=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='listings.vehicle')),
            ],
        ),
    ]
